# Generated by Django 3.2.16 on 2023-12-07 15:00

import contest.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(help_text='Рекомендованная розничная цена', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100), contest.validators.validate_price], verbose_name='Цена')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('image', models.ImageField(blank=True, upload_to='contest_images', verbose_name='Изображение')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='unique_title_contest'),
        ),
    ]
