# Generated by Django 3.2.16 on 2023-12-05 18:57

import contest.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='price',
            field=models.IntegerField(help_text='Рекомендованная розничная цена', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100), contest.validators.validate_price], verbose_name='Цена'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='unique_title_contest'),
        ),
    ]
