# Generated by Django 3.2.16 on 2023-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20231205_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, upload_to='contest_images', verbose_name='Изображение'),
        ),
    ]
